[tool.poetry]
name = "qa-net"
version = "0.1.0"
description = ""
authors = ["i.lobusov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.2.2"
ruff = "^0.5.0"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
